services:
  db:
    image: postgres:15-alpine
    container_name: sister_postgres
    environment:
      POSTGRES_DB: sister_cms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: sister_backend_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sister_cms
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - db