apiVersion: apps/v1
kind: Deployment
metadata:
  name: sister-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sister-frontend
  template:
    metadata:
      labels:
        app: sister-frontend
    spec:
      containers:
      - name: frontend
        image: sister-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sister-frontend-service
spec:
  type: NodePort
  selector:
    app: sister-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020  # ğŸ’¡ å¦³ä¹‹å¾Œå¯ä»¥é€é http://localhost:30020 è¨ªå•ç¶²ç«™